AWSTemplateFormatVersion: "2010-09-09"
Description: 

# ------------------------------------------------------------#
#  Metadata
# ------------------------------------------------------------#
Metadata:
    "AWS::CloudFormation::Interface"
    ParameterGroups:
        - Label:
            default:
          Parameters:
            -
    ParameterLabels:
            
# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------# 
Parameters:

# ------------------------------------------------------------#
# Resources
# ------------------------------------------------------------# 
Resources:
    xxx:
        Type:
        Properties:

# ------------------------------------------------------------#
# Output Parameters
# ------------------------------------------------------------# 
Outputs:
    xxx:
        Value:
        Export:
            Name:
